### ISSUE TITLE
Signal recording

### ISSUE THREAD

**Issue by Anyeos** [OpenHantek/OpenHantek6022#100]
**Is your feature request related to a problem? Please describe.**
As Audacity is for audio signal recording It will be very helpful to have the hability of recording the signal for future use on this software.
I need to analize a signal that is more than one second long but I need to look at the microsecond level detail on all the one second period. 
Actually I can do something like that just increasing the timebase and using zoom. But it is not possible to make a detailed time analysis because the samplerate is low.

**Describe the solution you'd like**
A button to record a few megabytes of signal on memory (the limit can be choosen on configuration). Next the recorded signal can be exported to disk.
The first proposed format maybe RAW (as is) with some header that specify the samplerate, bit depth and some other things.

**Describe alternatives you've considered**
Use my sound card with Audacity.
Modify the source code of this software to dump the buffer to disk.

**Additional context**
I have no all the experience on this software just to suggest more complex solutions. I know that with some modifications can break some other functionality. So special care must be taken and that is why for now I cannot suggest more.

It is an early idea and eventually will be modified by the passing of the time.
Suggestions and brainstorming are welcome

**Comment by Ho-Ro** [comment]
You can try this:
https://github.com/Ho-Ro/Hantek6022API#use-the-device-as-a-data-logger
see also #72 
Rationale: OpenHantek6022 cannot record gapless more than 4 MByte (due to USB protocol limitations), but the firmware allows to sample permanently for an unlimited long time and store the values, this is supported by `capture_6022.py`.
