### ISSUE TITLE
Calibration file problem

### ISSUE THREAD

**Issue by spam-receiver** [OpenHantek/OpenHantek6022#105]
Found out under Fedora 32 Linux:
Calibration file ~/.config/OpenHantek/modelDSO6022.ini alone do not change anything.
Calibration file ~/.config/OpenHantek/modelDSO6022.conf alone do not change anything too.
But if both these files exist in directiory, then calibration data applies from modelDSO6022.conf.

I could not figure out where to place the calibration file under Windows. Apparently, even all the settings are written to the registry.

**Comment by spam-receiver** [comment]
I could not figure out where to place the calibration file under Windows. Apparently, even all the settings are written to the registry.

**Comment by Ho-Ro** [comment]
Now it should work with an ini file alone, an existing `model*.conf` will be renamed automatically to `model*.ini`.
Regarding the ini file location please check this [Qt doc](https://doc.qt.io/qt-5/qsettings.html#locations-where-application-settings-are-stored):

    Linux/FreeBSD/macOS: $HOME/.config/OpenHantek/modelDSO6022.ini
    Windows: %APPDATA%\OpenHantek\modelDSO6022.ini

**Comment by spam-receiver** [comment]
Thanks!
