### ISSUE TITLE
Corrected openhantek.spec file to generate RPM packages in Fedora 32 Linux

### ISSUE THREAD

**Issue by spam-receiver** [OpenHantek/OpenHantek6022#106]
Added:
1) Group: Application/Engineering
2) %doc readme.md CHANGELOG docs/OpenHantek6022_User_Manual.pdf **_docs/HANTEK6022_AC_Modification.pdf_**

[openhantek.zip](https://github.com/OpenHantek/OpenHantek6022/files/4899622/openhantek.zip)

**Comment by Vascom** [comment]
Group tag should not be used for Fedora.
openhantek package already jn the official Fedora's repo.

**Comment by spam-receiver** [comment]
OK
