### ISSUE TITLE
Probe attenuation: limit number of possibilities

### ISSUE THREAD

**Issue by vizkoze** [OpenHantek/OpenHantek6022#107]
**Is your feature request related to a problem? Please describe.**
Before version 3.0.1, probe selection was limited to 1x or 10x. Some feature requests were made to append more types of (differential)probes going from 1X to 1000X. (Pull requests 50 and 51)
In current version, switching from 1x to 10x needs nine scroll actions to get to 10x. I wonder how long somebody with a 500x probe would take to get to his value.

**Describe the solution you'd like**
It would be neat to have a settings tab where you could define the probes you need, e.g. 1x, 10x and 500x. All other values would be omitted in the selection box.
if a settings tab would be too much work, a simple txt file in .config/ would be enough. 
if txt file exist, use values defined in txtfile, else use full range 
(i'm not a programmer so don't know if this is a lot of work)

**Describe alternatives you've considered**
Didn't consider alternatives because it is only a minor annoyance. the software is still way better than standard hantek soft

**Additional context**
no additional context given. keep up the good work

**Comment by Ho-Ro** [comment]
> I wonder how long somebody with a 500x probe would take to get to his value.

Just double-click in the probe attenuation field and write 500.

As you can see from history (e.g. #37) there are so many different wishes that I finally decided to  solve it like it is.
