### ISSUE TITLE
could not install openhantek on openSuse Leap 15.1

### ISSUE THREAD

**Issue by CampoES** [OpenHantek/OpenHantek6022#112]
**Describe the bug**
I tried to install openhantek-20200729_95ff65f-1.x86_64.rpm by Yast and got the following message:

qt5-qttranslations(x86-64) needed, but there is no source (Translation from German).

**Computer environment (please complete the following information):**

 - OpenHantek version: not installable.
 - OS: openSuse Leap 15.1
 - KDE-Plasma-Version 5.12.8, KDE-Framworks-Version 5.55.0, Qt-Version 5.9.7, Kernel-Version 4.12.14-lp151.28.59-default, 64 Bit
- Hardware: 4xIntel Core i5-7200 CPU @ 2.50 GHz, 7,6 GiB Ram
 - Video hardware: Integrated Graphics - Lenovo
 - OpenGL version: 3.0 Mesa 18.3.2
 - Qt version: 5.9.7
 - C++ compiler version: gcc-c++ 7l-p.151.3.5

**Scope device (please complete the following information):**
 - Device Hantek 6022BE
 - Program top line ?
 - Input signal: 
 - Probe setting: 

**Additional context**

**Comment by Ho-Ro** [comment]
Please try [this rpm](https://github.com/OpenHantek/OpenHantek6022/releases/download/unstable/openhantek-20200823_2fdc850-1.x86_64.rpm) in the latest [unstable release](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable).
