### ISSUE TITLE
Ability to set font size via .conf

### ISSUE THREAD

**Issue by technosf** [OpenHantek/OpenHantek6022#113]
OpenHantek UI starts up with an **_unreadably_** small font on my hw/s/w setup.

Unable to see any menu options to set font size, I would like to have font config options in the OpenHantek6022.conf so I can up date the settings. 

Settings would be font and font size

TY!

**Comment by Ho-Ro** [comment]
> on my hw/s/w setup

Please provide an useful amount of information about your setup - e.g. hardware, OS, distribution, screen resolution, maybe a screen shot, ...

**Comment by technosf** [comment]
Linux Mint 
![Screenshot from 2020-08-27 05-31-16](https://user-images.githubusercontent.com/535060/91442985-891d7880-e827-11ea-8dad-c008dca73bf2.png)

5.4.0-42-generic #46-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
2736x1824 (3:2), 60hz, 2x scale -> 1368x912 scaled resolution

**Comment by Ho-Ro** [comment]
This is not a recent OpenHantek6022 version - isn't it? Where did you get it?

The 1st screen looks different since about one year.

![image](https://user-images.githubusercontent.com/12542359/91449073-f3abd400-e87a-11ea-831a-dddc970f469a.png)

**Comment by technosf** [comment]
Installed from the 3.1.2 release file: openhantek_20200729-95ff65f_amd64.deb

**Comment by Ho-Ro** [comment]
> openhantek_20200729-95ff65f_amd64.deb

Nope!

Please provide the output of 
`OpenHantek -v`
and  
`which OpenHantek`

I guess you have an old install elsewhere, e.g. in `~/bin` or `/usr/local/bin`

**Comment by technosf** [comment]
Install is good:
```
/usr/bin/OpenHantek
OpenHantek6022 3.1.2
```
I think I've found the issue - its Qt5 interacting with the display scaling - Using the display magnifier and the Qt5 settings app I knocked the Qt5 fonts up into the 30point range and it is now close to your image above.

Thank you for your quick attention to this ticket and for you work on OH6022!

**Comment by Ho-Ro** [comment]
One question, where does this tabbed window in your screen shot come? It is no more in OH6022, I removed the tabs about one year ago. OH6022 also does not support only DSO-6022BE and DSO-6022BL, but also some other compatible devices, as well as a DEMO mode (as seen in my screen shot above).

![image](https://user-images.githubusercontent.com/12542359/91460689-62435e80-e888-11ea-9802-6409cf8ead8f.png)

**Comment by technosf** [comment]
The font setting does not affect the font size. I tried with "-f" and "--fontsize" with various values. 

This was in the terminal on running:
_qt5ct: using qt5ct plugin_

Not sure about the tabs - they are not there now. I keep an eye out to see if I recreate that.

**Comment by Ho-Ro** [comment]
You can try these options: https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by technosf** [comment]
My QT:
_QMake version 3.1
Using Qt version 5.12.8_

QT_SCALE_FACTOR: scales the font and the layout, so OpenHantek is too big to be usable, and the font still hard to read without the chang of fonts size in qt5ct.conf. 

The other env. variables had no effect on on the layout scaling nor the font rendering.
