### ISSUE TITLE
No need to escalate privilege for building the debian package...

### ISSUE THREAD

**Issue by Creteil** [OpenHantek/OpenHantek6022#114]
Hi,

In the process of building « debian » package, you can replace this step :

`sudo rm -f packages/*`
`sudo make package`
`sudo apt install packages/openhantek_*_amd64.deb`

by :

`rm -f packages/*`
`fakeroot make packages`
`sudo apt install packages/openhantek_*_amd64.deb`

No need to escalate privilege for building the package...

Regards.

**Comment by Ho-Ro** [comment]
The `fakeroot` solution is exactly the way I build locally. The documentation is now updated accordingly.
Thx for your hint.
