### ISSUE TITLE
Is there a way to compile on PPC arch?

### ISSUE THREAD

**Issue by MoMoPouetDev** [OpenHantek/OpenHantek6022#115]
**Additional context**
I'm about to get an old G3 based on PPC arch and I wonder if it is possible to build on this arch or not? 
Thanks

**Comment by Ho-Ro** [comment]
If no PPC user can answer you have to try it on your own. 1st step would be to check the availability of all required libraries (libusb fftw qt5 cmake).

**Comment by MoMoPouetDev** [comment]
Yes I've already check especially for qt5 and on Tiger 10.4 the last version available is 4.8. So ...
