### ISSUE TITLE
OpenHanotek hangs in macOS 11.0

### ISSUE THREAD

**Issue by sergiocampama** [OpenHantek/OpenHantek6022#117]
**Describe the bug**
After opening the .app, it hangs forever. Attached is a spindump of the process

**To Reproduce**
1. Download version 3.1.2 for macOS on a macOS 11.0 installation.
2. Open it

**Expected behavior**
Expected app to open

**Screenshots**
App doesn't open

**Computer environment (please complete the following information):**
 - OpenHantek version: 3.1.2 release from releases
 - OS: macOS 11.0 beta (20A5364e)
 - Distribution, version: MacBook Pro 16"

**Scope device (please complete the following information):**
 - Device DDS120 (but app hangs with the device connected or not)

**Additional context**
Add any other context about the problem here, e.g. the program output if started in a console like xterm.

[sample.txt](https://github.com/OpenHantek/OpenHantek6022/files/5177718/sample.txt)

**Comment by Ho-Ro** [comment]
@sergiocampama  Did you try to compile it on your system?

**Comment by Ho-Ro** [comment]
I have the feeling that you are no longer interested in this subject - will close now.
