### ISSUE TITLE
Need to add horizontal line for threshold in normal mode

### ISSUE THREAD

**Issue by Vascom** [OpenHantek/OpenHantek6022#118]
Can you please add horizontal line for "Normal" mode threshold?

Currently it is only mark at the right edge.

May be should be added option in settings to on/off showing this line.

**Comment by Ho-Ro** [comment]
You're thinking of something like this?
![image](https://user-images.githubusercontent.com/12542359/92884021-bf571c80-f411-11ea-9416-ead7336ee060.png)

**Comment by Vascom** [comment]
Yes.

**Comment by Ho-Ro** [comment]
Just to understand, what is your use case?

**Comment by Vascom** [comment]
I have wide screen. And horizontal line much more comfortable instead of small marker at the right and Voltage threshold value at the left.

**Comment by vizkoze** [comment]
Could be handy to see the horizontal line only while adjusting the trigger marker. It wouldn't clutter the screen

**Comment by DaPa** [comment]
I think most oscilloscopes nowadays show the line only when adjusting the trigger level but then taken off, as @vizkoze suggested...

**Comment by Vascom** [comment]
I do not mind.

**Comment by spam-receiver** [comment]
> I think most oscilloscopes nowadays show the line only when adjusting the trigger level but then taken off, as @vizkoze suggested...

I'm for that too!

**Comment by spam-receiver** [comment]
> Could be handy to see the horizontal line only while adjusting the trigger marker. It wouldn't clutter the screen

I'm for that too!

**Comment by Ho-Ro** [comment]
also available as latest [unstable release](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable)

**Comment by vizkoze** [comment]
nice improvement. thank you
