### ISSUE TITLE
High CPU load when paused

### ISSUE THREAD

**Issue by white-dragon** [OpenHantek/OpenHantek6022#123]
when paused on UltraHD on my I7-7700T its eats about 50% CPU (of one core)
mayb it useless cyclic rendering static image?

**Comment by Ho-Ro** [comment]
You can lower CPU load by setting menu: Oscilloscope/Settings/Scope -> Minimal time between... to minimal 1ms. 
The permanent rendering is necessary because you can change the settings (e.g. voltage, timebase or trigger position) and the "static" image changes.

**Comment by white-dragon** [comment]
and why u cant render new static image when settings change?

**Comment by Ho-Ro** [comment]
... because this has low priority for me.
You are welcome to send a pull request.
