### ISSUE TITLE
Documentation suggestion: explain how to get back a control panel after closing it

### ISSUE THREAD

**Issue by bcrowell** [OpenHantek/OpenHantek6022#124]
Several of my students have clicked the [x] to get rid of one of the control panels (e.g., Horizontal) and were then unable to figure out how to get it back. It took me a while to figure out myself how to do this, by right-clicking in the gray, blank area. It would be helpful to have this in the documentation.

Better yet, I think it would improve usability to have four items in the View menu that would give a separate way to control which panels are displayed. This would be easily discoverable by users.

**Comment by Ho-Ro** [comment]
Easy fix, I disabled the possibility to close the docks -  I don't see any reason to close these important UI elements - only the spectrum settings are not mandatory to use the scope.
Thx for reporting this issue - sometimes I cannot see the forest for the trees.
