### ISSUE TITLE
deb version for 32bit procesors

### ISSUE THREAD

**Issue by gitwasi** [OpenHantek/OpenHantek6022#125]
Hi, Can anybody add debian binary package version for older 32bit processors for example Atom N270?

**Comment by Ho-Ro** [comment]
The build process on deb is straight forward, just follow the [documentation](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/build.md#linux). Feel free to ask for help if it doesn't work.

**Comment by gitwasi** [comment]
I had to install fakeroot (on Debian 10.6, LXQT) and then it works. Thanks

**Comment by Ho-Ro** [comment]
Documentation fixed with f52e97e, thx for your feedback.
