### ISSUE TITLE
Noise filtering on trigger

### ISSUE THREAD

**Issue by alpytron** [OpenHantek/OpenHantek6022#127]
It would be a nice feature if the trigger could apply some filtering to make it more reliable on noisy signals.

Commercial oscilloscopes have such feature, so I guess it won't be too difficult to implement.

Below is a simple example what happens when there is a little amount of noise on the signal. Note that trigger slope is set to rising edge, still sometimes it triggers on falling edge as well.
![trg](https://user-images.githubusercontent.com/40063267/98452101-a1294680-214c-11eb-80e5-64483b90deb5.png)

**Comment by Ho-Ro** [comment]
Please try the trigger setting "smooth":

![image](https://user-images.githubusercontent.com/12542359/98452807-f7998380-2152-11eb-9b07-299c7e9c445f.png)

**Comment by alpytron** [comment]
Thanks for the advice, I was not aware of that item in the Source list. 
I tested it, and it woks quite, however sometimes I still got unstable triggering:
![image](https://user-images.githubusercontent.com/40063267/98481595-92e63380-21fb-11eb-83bc-7be072cc95ce.png)

Maybe it would be good to expose the smoothing/filtering parameter(s) to the user somewhere. Is that something feasible?

**Comment by Ho-Ro** [comment]
Binaries of this version are available as latest [unstable release](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable).

**Comment by alpytron** [comment]
Thank you, Ho-Ro!
Selecting LF works perfectly for low frequency noisy signals. Great job! :)
