### ISSUE TITLE
Dummy load power show

### ISSUE THREAD

**Issue by bmsorin** [OpenHantek/OpenHantek6022#129]
Hello,

Because i mainly work on audio projects, i consider to be a good addition to show the power RMS on the main dock.
I have made this modification it look something like this:
![Screenshot at 2020-11-14 10-50-20](https://user-images.githubusercontent.com/74449645/99144001-00b2b500-266b-11eb-9cdb-34066c824694.png)
![Screenshot at 2020-11-14 10-50-37](https://user-images.githubusercontent.com/74449645/99144002-01e3e200-266b-11eb-8bae-89598dd91cef.png)

[patch-3.1.3.diff.zip](https://github.com/OpenHantek/OpenHantek6022/files/5540423/patch-3.1.3.diff.zip)

Attached the diff file for v3.1.3 if someone is interested.

Regards!

**Comment by Vascom** [comment]
How you calculate the power?

**Comment by bmsorin** [comment]
(Vrms*Vrms)/dummy load

**Comment by bmsorin** [comment]
i use this formula
(analysedData.get()->data( channel )->rms*analysedData.get()->data( channel )->rms)/view->dummyLoad

**Comment by Vascom** [comment]
I understand. Thanks.
Seems as good improvment. Can you make Pull Request?

**Comment by bmsorin** [comment]
Unfortunately i can't make a pull request.
I have take the master branch, create new branch locally, apply the pacth, check all is ok, but when i want to make a push with new branch, i got permission denied, can you tell me what i make wrong?

$ git branch -a
* dummy_load
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/cleanup_6022
  remotes/origin/last_legacy_support
  remotes/origin/master

$ git push -u origin dummy_load
ERROR: Permission to OpenHantek/OpenHantek6022.git denied to bmsorin.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Regards!

**Comment by Vascom** [comment]
You need clone the repo at github. Make your changes. Press button "Create Pull Request".
It is github feature, not git.

**Comment by bmsorin** [comment]
ok, here you go
https://github.com/OpenHantek/OpenHantek6022/pull/130

**Comment by Ho-Ro** [comment]
Hi, good idea. As a small change I would move the resistance setting from scope into the next tab (currently named  *spectrum*, renamed to *analysis* with subsections *spectrum* and *power*). I will check ..

**Comment by Ho-Ro** [comment]
Thx, I merged your #130 with the changes mentioned above.

**Comment by bmsorin** [comment]
Thank you!
