### ISSUE TITLE
Interface change 

### ISSUE THREAD

**Issue by zen67** [OpenHantek/OpenHantek6022#135]
Hi!
Is it possible to change interface as picture below (with or without divider line)?
Everything is grouped in one place (оne eye movement less).
Thanks!

![Clip](https://user-images.githubusercontent.com/24452842/101285385-8e5a6e00-37ed-11eb-9724-0cc01c284e4f.jpg)

**Comment by Ho-Ro** [comment]
Thanks for the suggestion, I will test it and think about whether I like it (it's only an easy change to dsowidget.cpp).

**Comment by Ho-Ro** [comment]
I like the classic layout better - otherwise the top line looks too naked :)
But as I said, it's an easy change...
