### ISSUE TITLE
GUI suggestion

### ISSUE THREAD

**Issue by zen67** [OpenHantek/OpenHantek6022#137]
Everything is grouped in one place, easy to tap without much mouse movement.
Everything happens faster.
A window space opens.
Is it possible to be a permanent / switchable option without dragging the tool bar?
Is there a possibility for 3D buttons?
![Clip](https://user-images.githubusercontent.com/24452842/101832109-942eb700-3b3f-11eb-8f76-a5c8ba9f637f.jpg)

**Comment by Ho-Ro** [comment]
> Is it possible to be a permanent / switchable option without dragging the tool bar?

You can drag the tool bar to the right border once and it will stay there - also after restart.
![image](https://user-images.githubusercontent.com/12542359/101982126-115a4900-3c72-11eb-9c61-3ce277188cf6.png)

> Is there a possibility for 3D buttons?
￼
I do not know - and honestly speaking I don't care about the buttons, the screen is important. For me the gui looks ok.

**Comment by zen67** [comment]
Linux build is OK.
Windows build is differеnt.
Еverything is smaller and 2D, unlike the Linux build, where the buttons are like 3d and everything is bigger and more convenient to work with.

**Comment by Ho-Ro** [comment]
This is how it looks on a W10 computer (screen size 1920x1080) - for me it doesn't look unusable:
![Screenshot 2020-12-12 193756](https://user-images.githubusercontent.com/12542359/101992290-733aa300-3cb2-11eb-88d9-d686dc076962.png)

**Comment by zen67** [comment]
I commented on the differences.
See the difference in the attached photos.
![1920x1200 Linux1](https://user-images.githubusercontent.com/24452842/101995862-ddb10a80-3cd5-11eb-993b-3c230d32d8b3.jpg)
![1920x1200 Windows1](https://user-images.githubusercontent.com/24452842/101995867-e275be80-3cd5-11eb-9147-9f19bfcae83c.jpg)

**Comment by Ho-Ro** [comment]
Ok, I rename this issue with the clear target of a Windows GUI enhancement.

@zen67 wrote:
> Linux build is OK.
Windows build is differеnt.
Еverything is smaller and 2D, unlike the Linux build, where the buttons are like 3d and everything is bigger and more convenient to work with.

The GUI style was set for Linux by `openHantekApplication.setStyle( QStyleFactory::create( "Fusion" ) );` in source file [main.cpp](https://github.com/OpenHantek/OpenHantek6022/blob/d16b3dc9dd452d57b1dc9052469ba48f57556e17/openhantek/src/main.cpp#L142). I do not use any Windows computer for development and the trial and error process via the web based CI tool appveyor is slow, so I here is one last test that applies the same style also for windows (d16b3dc), also available  from *"[unstable](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable)"*. 
This is how this looks fullscreen on a 1920x1080 win laptop:

![image](https://user-images.githubusercontent.com/12542359/102069379-f9173500-3dfd-11eb-85bc-04bc105cf76a.png)

**Comment by zen67** [comment]
Thanks!
It's much better now, but it's still a little smaller than Linux.
Is it possible to have an autodetect of screen resolution to eliminate this forever?
That's what it looks 
![Clip](https://user-images.githubusercontent.com/24452842/102081753-64bacb80-3e19-11eb-88c0-1ce217a51ca6.jpg)

**Comment by Ho-Ro** [comment]
You can also play with the environment variable QT_SCALE_FACTOR

    set QT_SCALE_FACTOR=1.5
    OpenHantek.exe

![image](https://user-images.githubusercontent.com/12542359/102121978-1fac8e80-3e45-11eb-9f72-fa7b59201d26.png)

**Comment by zen67** [comment]
Thanks!
Font change works just fine!!!
Where in the source, can the font size be specified?
The font can also be changed through shortcut ("C: \ Users \ ..... \ Desktop \ Hantek \ OpenHantek-Win-x64 \ OpenHantek.exe" -f 10), but it is inconvenient to does every time (for example when you make a new shortcut)
Screenshot (font = 10)
![Clip_2](https://user-images.githubusercontent.com/24452842/102210834-5fbe5080-3edb-11eb-83a5-d56926de42e9.jpg)

**Comment by Ho-Ro** [comment]
[main.cpp#L100](https://github.com/OpenHantek/OpenHantek6022/blob/5ef84a9524b0ef8c679750cb9ed7625a13b46e97/openhantek/src/main.cpp#L100): `const int defaultFontSize = 10;`

**Comment by zen67** [comment]
const int defaultFontSize = 10;
increases font too much (screenshot 1)
When OpenHantek.exe -f 10 is used, the font becomes smaller and everything comes close to the Linux build
(screenshot 2).
(Screenshot 2 is from the last build, but OpenHantek.exe -f 10 was used.).
Screen 1
![Clip_1](https://user-images.githubusercontent.com/24452842/102242592-e33f6800-3f02-11eb-9ea0-826f0750f267.jpg)


Screen 2
![Clip_2](https://user-images.githubusercontent.com/24452842/102242609-e89cb280-3f02-11eb-9b3e-4a527e812bcb.jpg)

**Comment by Ho-Ro** [comment]
So, next step - the font size can also be changed in the settings menu (and become active after a restart). Available in unstable:
![image](https://user-images.githubusercontent.com/12542359/102266726-20aef000-3f19-11eb-9d75-9db222f0293f.png)
Are you already able to build your own version for Widows as well as Linux?

**Comment by zen67** [comment]
Great!
Changing the font works fine now.

_Are you already able to build your own version for Widows as well as Linux?_
Own - hardly.
I manage to create a 48MS/s version for the experiments I do with the hardware (through appveyor.com).
