### ISSUE TITLE
Automated CSV saving using OpenHantek

### ISSUE THREAD

**Issue by mbobinger** [OpenHantek/OpenHantek6022#149]
Thank you a lot for your great package! I've enjoyed using it on my RaspberryPi. I didn't manage to get PyVisa working with the RPI nor with a WINDOWS PC with the Hantek6022BE.

Since this is a low-cost PC oscope and widely used, it would be so practical to have it save CSV files automatially with predefined settings so the user can do some computation on the data.

Is there any way to automate data saving using OpenHantek?
Thank you!

**Comment by Ho-Ro** [comment]
same as #148
