### ISSUE TITLE
RPi 4B Touch Screen

### ISSUE THREAD

**Issue by Peter847** [OpenHantek/OpenHantek6022#161]
I have an issue running OpenHantek 3.2 on an RPi with a 7" touchscreen using the latest version of the default (Debian) OS.  I lose the bottom quarter of the screen so, for example I cannot see anything below the "Configuration" title on the settings page.  Although I do see the bottom of the actual scope display.  I suspect this may be more of a Pi issue than an OpenHantek issue as the touchscreen has a non-standard resolution of 800 x 480.  I have setup the Pi to recognize this resolution and it seems to work on ok on the standard desktop.

Any thoughts on what I could do to fix it would be much appreciated!

**Comment by Ho-Ro** [comment]
You can shrink the main window down to 790x299 (on my KDE Debian system) when you tab the docks. But the config screen has a fixed size of 844x615 on my system due to the chosen software architecture. A quick workaround (you do not use this screen permanently) could be to use `<ALT><mousedrag>` to the lower part into reach.

![image](https://user-images.githubusercontent.com/12542359/110915456-f0a89a80-8317-11eb-9469-7170e3f8d707.png)

**Comment by Peter847** [comment]
Martin

Many thanks for the information.  I used the screen sizes to set
framebuffers in the Pi and I can now see the whole page.  However I am
getting a little confused on how the panel/tabs work but I don't see
anything in the manual on them?

Peter

**Comment by Ho-Ro** [comment]
The tabbed docks are standard Qt QDockWidgets, you can grab them by their title line (e.g. Voltage, Horizontal, ..), rearrange them or drag them around on your screen.

![image](https://user-images.githubusercontent.com/12542359/111190369-4c448380-85b7-11eb-924c-2a1845ba5483.png)

To put them back just click the top right small button or drag them over the docking area until an **empty** blue space opens and drop it there.

![image](https://user-images.githubusercontent.com/12542359/111190215-2ae39780-85b7-11eb-89b8-e4bf1caf3b22.png)

If you drag a floating dock over another dock the target dock will turn blue. Drop the dock and it will be tabbed together with the target dock. 

![image](https://user-images.githubusercontent.com/12542359/111192075-f96bcb80-85b8-11eb-9c7e-48cdf9cc89f7.png)

This way you can combine all docks into one tab as I did in my 1st screen shot some days ago. Also the order of the tabs can be changed by dragging them left or right.

I will update the manual next time I touch it.
