### ISSUE TITLE
Grid dots are difficult to see

### ISSUE THREAD

**Issue by staticmem** [OpenHantek/OpenHantek6022#17]
Depending on the viewing angle the grid dots are very difficult to see.  Can these be made larger using more pixels perhaps with an option in the colour configuration menu?

**Comment by Ho-Ro** [comment]
Have you already increased the alpha channel value of the grid in the colour menu? The default value is 0xBF, set it to 0xFF.
The definition of the colours happens in viewsettings.h, e.g. line 32
` QColor(0xff, 0xff, 0xff, 0xff), QColor(0xff, 0xff, 0xff, 0xbf), // border, grid`

**Comment by staticmem** [comment]
Thanks. That solved it but I think my default value was lower than what you stated.  Maybe it should be raised?

**Comment by Ho-Ro** [comment]
It was already raised from 0x3F to 0xBF with ff01faf but if you started with an earlier version it has been kept in the automatically stored config file.
