### ISSUE TITLE
Single Trigger question

### ISSUE THREAD

**Issue by No13** [OpenHantek/OpenHantek6022#18]
First of all, huge thanks for this piece of software. The original OpenHantek was a bit hard to use with the 6022BE regarding triggers...

Perhaps it is a lack of understanding the feature, perhaps it is a feature that could be implemented differently but my question is as follows:

When i have a signal that's not repeating, (for instance an IR command, measured at the sending IR LED) I can select trigger mode Normal. The program wil wait for a trigger and display the waveform.

However, If I get a repeating signal, for example 1 IR command every 200ms, the trigger mode 'Normal' will be updating every time. This is where trigger mode 'Single' would be used, at least, that's what I expected?

Instead: Single mode always fire's instantaneous when pressing the 'play' button. Whether the trigger condition is met or not (In the upper left corner, you see a nice red TR when the trigger condition was not met). Is this the expected behaviour? And is my use-case invalid for this type of device? Using the Windows Software, it appears 'Single' will wait for a trigger, fill the... buffer? and stop collecting after the buffer is full. This allows to capture an event based on the trigger and analyse after the fact...

Kind regards,

Eric van Zandvoort

Edit: I tried to accomplish what i described but my programming skills are a bit rusty :)
It seems to be working on a basic level :)
[single-mode.txt](https://github.com/OpenHantek/OpenHantek6022/files/3520498/single-mode.txt)

**Comment by Ho-Ro** [comment]
Dear Eric,

Thank you for pointing out this issue **and** providing a patch, this meets the purpose of GitHub. I like the "live" display of the not triggered trace that freezes as soon as the trigger condition is met. For my understanding it gives more info than showing a blank screen or a long gone event.

Martin
