### ISSUE TITLE
Provide a option to choose language?

### ISSUE THREAD

**Issue by cdhigh** [OpenHantek/OpenHantek6022#191]
**Is your feature request related to a problem? Please describe.**

Some translations may be wrong or difficult to understand. In this case, it may be necessary to switch to English temporarily, but it is currently not possible.

**Describe the solution you'd like**

Can provide an option in the configuration dialog to select different languages?

**Comment by Ho-Ro** [comment]
You already have two possibilities to change the language:
1. Use command line option `Openhantek -i` (or --international) to skip the translation completely and get the original English text.
2. Use environment variable LANG to select what you want, e.g. `LANG=fr OpenHantek` switches to French, while `LANG=C ...` disables translation at all.

The setting in the configuration dialogue cannot change the language selection immediately, a shutdown/restart is necessary to change the localisation as the texts have to be loaded when the application starts.

**Comment by cdhigh** [comment]
Now that there is a workaround, it can not be implemented.
Agree
