### ISSUE TITLE
Return system theme 

### ISSUE THREAD

**Issue by Nikita-Presnov** [OpenHantek/OpenHantek6022#192]
I can't say that I am strongly against other topics, but fusion is really painful to look at after breeze.

**Comment by Ho-Ro** [comment]
The reason for Fusion is simply the smaller size on screen. Fusion (837x662) fits perfectly on the screen of an older HD1280x720 (or 1024x768) Laptop, while Breeze (837x795) collides with the statusbar. But now you can get the Breeze theme with command line option `OpenHantek -b` or`OpenHantek --breeze`, available in latest [unstable release](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable). 

![Fusion](https://user-images.githubusercontent.com/12542359/122964613-ba070500-d387-11eb-8e77-901ea3b00575.png)

![Breeze](https://user-images.githubusercontent.com/12542359/122964559-aeb3d980-d387-11eb-973d-543f21a23150.png)

**Comment by Nikita-Presnov** [comment]
Thank you

**Comment by Ho-Ro** [comment]
@Nikita-Presnov No command line option anymore, you can now select "Fusion" in options Oscilloscope / Settings / Color
-> unstable

**Comment by Nikita-Presnov** [comment]
Okay
