### ISSUE TITLE
The Hold-off Trigger Control

### ISSUE THREAD

**Issue by KanKub** [OpenHantek/OpenHantek6022#196]
Is it possible to implement hold-off control to 6022BE? it would be a lot easier to diagnose the logic signal.

**Comment by Ho-Ro** [comment]
As the Hantek has no HW trigger everything has to be done in SW - fetch one block, search for a trigger condition and display. So no chance to delay more than one screen width. Sorry, this is a very limited HW.
But if you want to check logic a [simple LA](https://sigrok.org/wiki/Lcsoft_Mini_Board) would be more sufficient.
