### ISSUE TITLE
Add DSO4104C ? 

### ISSUE THREAD

**Issue by jpmlima** [OpenHantek/OpenHantek6022#20]
Is it possible to add DSO4104C?
I don't know how i can add this because firmware of DSO is in .upk and i need to add hex file...
Anyone can help me ?
Thanks

**Comment by Ho-Ro** [comment]
OpenHantek6022 works only (as the name implies) with Hantek6022 and compatible scopes. But you can try to adapt [openhantek](https://github.com/OpenHantek/openhantek) that addresses a wider range of Hantek devices. You need to extract the firmware as hex file _and_ provide also the codes and data structures for USB communication. Have a look at [this post](https://www.eevblog.com/forum/testgear/hantek-6022be-20mhz-usb-dso/msg661511/#msg661511) to see how it can be done.
