### ISSUE TITLE
Main window size issue

### ISSUE THREAD

**Issue by milestab9** [OpenHantek/OpenHantek6022#228]
The main window is larger (deeper) than the screen. The bottom can't be seen unless the window is moved. The window can't be maximized.

The infomations present at the bottom (peak to peak voltage, frequency ...) can't be seen unless the window is moved.

I'm using Fedora 34, OpenHantek6022 3.2.4.

**Comment by Ho-Ro** [comment]
What is your screen resolution? Also check #192 or play with the *Fusion* style and font size. 
Either from command line options:
````
OpenHantek6022 (3.2.4)
Usage: OpenHantek [options]

Options:
  -?, -h, --help               Displays help on commandline options.
  --help-all                   Displays help including Qt specific options.
  -v, --version                Displays version information.
  -d, --demoMode               Demo mode without scope HW
  -e, --useGLES                Use OpenGL ES instead of OpenGL
  --useGLSL120                 Force OpenGL SL version 1.20
  --useGLSL150                 Force OpenGL SL version 1.50
  -i, --international          Show the international interface, do not
                               translate
  -f, --font <Font>            Define the system font
  -s, --size <Size>            Set the font size (default = 10, 0: automatic
                               from dpi)
  -c, --condensed <Condensed>  Set the font condensed value (default = 87)
  --resetSettings              Reset persistent settings, start with default
  --verbose <Level>            Verbose tracing of program startup, ui and
                               processing steps
````
or from settings menu:
![image](https://user-images.githubusercontent.com/12542359/136157125-77b08d4d-85e3-4508-bc2c-8df37a6a8f52.png)

**Comment by Ho-Ro** [comment]
> It's an old laptop with a 15.4" screen and a resolution of 1200x800.

These older laptops are often used in labs - I recently retired an original IBM ThinkPad A21 after 20 years of service ;)
I had this kind of HW in mind when I decided long ago to use *Fusion* as the default style, but after getting some complaints about it looking *strange* with other programs open, I made *Fusion* a configuration option. Also the manual explains (bottom of p.14) how to use this style for smaller screens.
