### ISSUE TITLE
Manual theme switch

### ISSUE THREAD

**Issue by mpekurin** [OpenHantek/OpenHantek6022#248]
As the title says, it would be nice to have an option in the settings or a command line option to manually set the program theme (auto, light or dark).

**Comment by Ho-Ro** [comment]
Hi Maxim, good proposal!
Please check the latest commit, also available soon as ["unstable"](https://github.com/OpenHantek/OpenHantek6022/releases/tag/unstable).
Theme (Auto/Light/Dark) can be set in menu "Oscilloscope/Settings/Colors".
![image](https://user-images.githubusercontent.com/12542359/145857409-f434ffe9-69a5-4531-b670-605a11f48a3a.png)
