### ISSUE TITLE
Background of marker selected rectangle area is transparent on Wayland

### ISSUE THREAD

**Issue by ericfont** [OpenHantek/OpenHantek6022#257]
When I drag a rectangle to select an area using measurement tool, I can see through the background of the oscilloscope to what is on my desktop underneath the OpenHantek window:

![opne-hantek-on-wayland](https://user-images.githubusercontent.com/6502474/148719715-56a75f41-35a5-46ce-b6f1-ce0a69289326.png)

I'm on Arch Linux 5.10.90-1-lts with latest packages from repos (wayland v1.20.0-1, xorg-xwayland v21.1.4-1, KDE plasma-desktop 5.23.5-1), using OpenHantek commit 944 (built via https://aur.archlinux.org/packages/openhantek6022-git/).

Maybe should report this to xorg-wayland people instead of you, cause it should be their responsibility.  (and maybe this also has to do with opengl too).

**Comment by ericfont** [comment]
I just noticed this issue on another program that use opengl, I think...so I'm sure this issue has to do with wayland and not your problem:

![candle-on-wayland-transparnet](https://user-images.githubusercontent.com/6502474/149057617-08cf87f1-10cb-4299-8c25-9e785c75efc3.png)

**Comment by ericfont** [comment]
For anyone reading, I can force usage of Xorg backend for Qt (so can have the opengl working) in a Qt app under a wayland session by having the environment variable `QT_QPA_PLATFORM=xcb` set when runnning...

**Comment by Ho-Ro** [comment]
Thx für investigating.
