### ISSUE TITLE
Why is the Measurements GUI background now white?  Almost impossible to read colored text now.

### ISSUE THREAD

**Issue by ericfont** [OpenHantek/OpenHantek6022#292]
Now I'm on OpenHantek6022 2022-04-14 commit 1003, on the default settings, and I notice the background color of the Measurements GUI area is slightly-off-white:

![image](https://user-images.githubusercontent.com/6502474/163922116-76d5ab9a-64a5-4a8a-a0d7-f35f9145aa5b.png)

This makes it almost impossible to read the colored text.

I remember this area used to be a darker color, cause I remember being able to read the Measurements!  Could you please revert back to the earlier darker colored used?

I'm on arch linux 5.15, Qt 5.12.8, Graphic 4.6 (Compatibility Profile) Mesa 22.0.1 - GLSL version 1.20, on latest KDE plasma desktop.  I don't think anything substantially has changed on my desktop since the earlier time I was able to read the marker text, so I think some recent commit to OpenHantek unintentionally changed this color.

**Comment by Ho-Ro** [comment]
I checked an I can confirm this regression for 2022-04-14 commit 1003, but only with system (Breeze) style:
![20220419_093144](https://user-images.githubusercontent.com/12542359/163950042-cb0cb73b-82f2-4748-86a2-42af605fce01.png)
Fusion works as expected:
![20220419_093211](https://user-images.githubusercontent.com/12542359/163950107-e82459a5-e3ec-4df5-9b52-8269704eb3b6.png)
I will investigate further...
