### ISSUE TITLE
Is it possible to make friends with a Hantek6022BE with a Bluetooth module?

### ISSUE THREAD

**Issue by zaxtone** [OpenHantek/OpenHantek6022#303]
Hi.  I use a google translator/
Hello connoisseurs. I wanted to ask first. Is it possible to make friends with a USB oscilloscope with a Bluetooth module?
In my case, this is [the damned hantek 6022be](https://sigrok.org/wiki/Hantek_6022BE), the filling is indicated.

In the presence there is this module [HC-06](https://www.olimex.com/Products/Components/RF/BLUETOOTH-SERIAL-HC-06/resources/hc06.pdf) which is connected via UART protocol

**Comment by Ho-Ro** [comment]
???
Do you ask if it's possible to add a bluetooth module and communicate wireless over bluetooth? No chance.
