### ISSUE TITLE
Size of viewpoint

### ISSUE THREAD

**Issue by nemanjan00** [OpenHantek/OpenHantek6022#304]
**Describe the bug**

![20220531_10h54m54s_grim](https://user-images.githubusercontent.com/448151/171134474-01734129-52a6-47e2-90d7-6aa4155cf734.png)

Viewpoint does not resize when I click with resize cursor and drag to resize

**To Reproduce**

Open program and try to resize

**Expected behavior**
Viewpoint should resize

**Screenshots**

![20220531_10h54m54s_grim](https://user-images.githubusercontent.com/448151/171134474-01734129-52a6-47e2-90d7-6aa4155cf734.png)

**Computer environment (please complete the following information):**
 - OpenHantek version: b46ab64866477a37fb5478dcac5742a0d42263b3
 - OS: Linux
 - Distribution, version: Arch with Wayland
 - Video hardware:  Intel® UHD Graphics for 8th Generation Intel® Processors
 - OpenGL version: Mesa 22.1.0-1
 - Qt version: Qt 5.15.3
 - C++ compiler version: gcc 12.1.0

**Scope device (please complete the following information):**
 - Device Hantek 6022BE
 - Program top line OpenHantek6022 (3.3.0) - Device  DSO-6022-BE (FW0210)
 - Input signal: no
 - Probe setting:no
**Additional context**

```
OpenHantek6022 (3.3.0)
Graphic: 4.6 (Compatibility Profile) Mesa 22.1.0 - GLSL version 1.20
```

**Comment by Ho-Ro** [comment]
If you use this *erroneous* laptop, please also check whether the sub-windows (e.g. the setup window) show comparable behaviour. But I suspect that [`DsoWidget`](https://github.com/OpenHantek/OpenHantek6022/blob/main/openhantek/src/dsowidget.cpp) (the black part of the scope) is causing this issue.

**Comment by nemanjan00** [comment]
Hello,
There is similar behavior in other windows too

![20220612_14h17m31s_grim](https://user-images.githubusercontent.com/448151/173232771-5b618f8d-3ff3-4f85-a2ec-68cecf13e355.png)

**Comment by nemanjan00** [comment]
Ok, I figured it out. It is related to QT theme I used

**Comment by nemanjan00** [comment]
Just in case you want to take a deeper look, since it is quite popular theme framework, it is Kvantum

**Comment by Ho-Ro** [comment]
Thank you for this info, I can confirm this issue with Kvantum and Kvantum dark (never used this theme before). A simple workaround would be to select "Fusion" style and "Dark" theme in menu Oscilloscope/Settings/Colors.

**Comment by Ho-Ro** [comment]
There is now a "hack" (c0a7fac) that switches to the dark fusion style when it detects "kvantum*" as the system style - you may have to manually correct the disturbed look once.

**Comment by jvandenbroek** [comment]
Thanks, I had the same issue. Not sure about that hack @Ho-Ro , I've installed the git version from AUR and still had this issue with Kvantum theme.

**Comment by Ho-Ro** [comment]
Which version does the program show in the top line?

**Comment by jvandenbroek** [comment]
Sorry for my late response, but you are absolutely right. Didn't realize the git version of AUR was that outdated. Now I've installed the recently released regular version (also from AUR). The issue still persists with kvantum-dark, but setting Fusion style in settings solves this.

**Comment by Ho-Ro** [comment]
> The issue still persists with kvantum-dark, but setting Fusion style in settings solves this.

Please unset Fusion, restart the program with `OpenHantek --verbose 1` and report the startup messages, normally it should select "Fusion" automatically if it detects "kvantum*". But nevertheless it's good that you found a workaround.
