### ISSUE TITLE
Gain calibration file for WIndows 10?

### ISSUE THREAD

**Issue by agentpatience** [OpenHantek/OpenHantek6022#307]
Hi Ho-Ro,

When trying to setup gain calibration I cannot find the proper path for %APPDATA%\OpenHantek\ xxxx_calbration.ini in Windows 10. This path is cited in the manual.

![image](https://user-images.githubusercontent.com/36264810/171668627-9a225420-307b-48f3-b2d4-9cf2f7143ad4.png)

**Comment by Ho-Ro** [comment]
Hi Jeff,
Opening `cmd.exe` and typing `echo %APPDATA%\OpenHantek\DSO-6022BE_NNNNNNNNNNNN_calibration.ini` will give you `C:\Users\Jeff\AppData\Roaming\OpenHantek\DSO-6022BE_NNNNNNNNNNNN_calibration.ini`.
You can create this file (replace NNN.. with your device ID, shown in "About") with a content like this (adapt the gain values accordingly):
````
[gain]
ch0\20mV=1
ch0\50mV=1
ch0\100mV=1
ch0\200mV=1
ch0\500mV=1
ch0\1000mV=1
ch0\2000mV=1
ch0\5000mV=1
ch1\20mV=1
ch1\50mV=1
ch1\100mV=1
ch1\200mV=1
ch1\500mV=1
ch1\1000mV=1
ch1\2000mV=1
ch1\5000mV=1
````

**Comment by Ho-Ro** [comment]
@agentpatience did this solve the issue?

**Comment by agentpatience** [comment]
Yes, thanks! I have a secondary problem. I want to use my DSO-2090 with this software but it doesn't seem to load? Is it compatiable?
