### ISSUE TITLE
Some errors when starting without an existing Version

### ISSUE THREAD

**Issue by a-n-d-i** [OpenHantek/OpenHantek6022#309]
I downloaded Openhantek6022 for the first time today and it showed some weird behavior:

- no roll mode
- refresh button not showing at all
- start/stop in single trigger mode does not clear the screen
- possibly more

![Screenshot from 2022-06-04 19-42-42](https://user-images.githubusercontent.com/6292768/172019361-1a76017e-e2c4-4798-8a2e-e051383a5841.png)

I installed a random version from last year, worked fine. Reinstalled 3.3.0, worked fine. Deleted the folder in ~.config, broken. 

Might be related to #308

**Comment by Ho-Ro** [comment]
> no roll mode

The roll mode only makes sense with a slow time base > 100 ms/div and is therefore only activated then. If you use an old configuration with activated roll mode at a faster time base, the roll mode remains, but switches to the slow time base of 200 ms/div.

> refresh button not showing at all

The refresh button is only useful in roll mode and is only displayed in this mode.

> start/stop in single trigger mode does not clear the screen

A free running screen is displayed until a new triggered trace is available. 

> Deleted the folder in ~.config, broken.

I did the same, removed ~/.config/OpenHantek, still works as I expect.

**Comment by Ho-Ro** [comment]
@a-n-d-i Any new findings?

**Comment by a-n-d-i** [comment]
@Ho-Ro No, haven't used the software any more, bought the scope to keep on my boat in case something to troubleshoot comes up.

**Comment by Ho-Ro** [comment]
Ok, then I will close for now - please reopen if necessary.
