### ISSUE TITLE
TortoiseSVN in process

### ISSUE THREAD

**Issue by tinwinaung** [OpenHantek/OpenHantek6022#31]
This is rather a question.
I can run latest OpenHantek-Win-x64-Release-b127.zip in my Windows 10 PC (1903).
However, I found TortoiseSVN under OpenHantek process. May I know why?

![2019-10-20 23_48_42-Task Manager](https://user-images.githubusercontent.com/1169631/67162200-6feca580-f394-11e9-8927-e388af66a1e8.png)

**Comment by Ho-Ro** [comment]
Tortoise SVN is not a part of OpenHantek6022. I don't know why it is shown in the OpenHantek context on your PC. OH is developed under git / github and therefore does not use TortoiseSVN or any other SVN.  Did you install TSVN on you computer?
