### ISSUE TITLE
Plot harmonic spur measurements

### ISSUE THREAD

**Issue by agentpatience** [OpenHantek/OpenHantek6022#317]
I would like the spectrum processor to show the value of the peak of the spur. I don’t see how to view these values in your software release.

**Comment by agentpatience** [comment]
![Uploading 3153B43F-4443-4F57-830A-ADE08444EC50.jpeg…]()

**Comment by Ho-Ro** [comment]
Press the right mouse button on the screen and move around to measure time/frequency and (if you're near a trace) voltage/amplitude at the cursor position.
![image](https://user-images.githubusercontent.com/12542359/180151849-69f92ff0-de0a-474c-b78e-3b8d9dd07816.png)
