### ISSUE TITLE
Duty cicle measurement

### ISSUE THREAD

**Issue by thalst** [OpenHantek/OpenHantek6022#32]
Hi,l. First of all, thanks for this amazing software! It definately runs smoother than any other available. The only thing I miss here is a duty cicle measurement, and other minor measurements such as rise and fall times, etc. Is it possible to implement these? I could not uninstall the original software only because I eventually need those measurements.

**Comment by Ho-Ro** [comment]
@thalst Good proposal! 
Please have a look at the latest commit 473221e
Now the top line shows the width of the pulse after trigger and the following pulse as well as the duty cycle: /1.00ms\999µs/ (50%)
![image](https://user-images.githubusercontent.com/12542359/68510472-f13ca700-0273-11ea-9524-18b770d5b0c2.png)

You can measure rise / fall time easily with the drafting compass menu on the left.

**Comment by thalst** [comment]
Awesome!!! Another question: do you have some material regarding the spectrum measurement and how to interpret it? I'm having a hard time finding the frequency for a given spike in SPx

**Comment by Ho-Ro** [comment]
That's easy, we have e.g. a 2kHz square wave with frequency peaks at 2, 6, 10, ... kHz. The horizontal dock let you select the frequency base for the display of the spectrum, in our case "Frequencybase 1kHz" (1kHz/div), so a peak at division 2, 6, 10.
![image](https://user-images.githubusercontent.com/12542359/68511652-b9832e80-0276-11ea-894c-eaef591fc2d4.png)
You can set the frequency resolution in the same way as the time domain per division -> same frequency, but with "Frequencybase 10kHz"
![image](https://user-images.githubusercontent.com/12542359/68512516-eafcf980-0278-11ea-8c3b-9c29c81718e2.png)
The bottom lines display also the fundamental frequency of the measured traces on the right (2.000 kHz).

**Comment by thalst** [comment]
I dont know how to thank you. It's a great work. I'll be throwing more ideas in a few days if you don't mind. 
I run a web hosting company. Feel free to contact me if you need a free lifetime web hosting!
