### ISSUE TITLE
Probes scale and custom probes

### ISSUE THREAD

**Issue by thalst** [OpenHantek/OpenHantek6022#33]
Hi, 

When opening the program, channel 1 probe's scaling is set to 10x, as I left it. But in order to the measures to be correck I have to uncheck and check the box again.

Also, is it possible to use custom attenuation probes? I'm plannig to make some DIY 4:1, 20:1 and 50:1 probes.

1. Open the program 
2. Check 10x at both channels
3. Close the program and open again
4. See that channel 1 in left lower corner is not corresponding to the scale set in the control panel

 - Device Hantek 6022BE

**Comment by Ho-Ro** [comment]
Thx for this finding and the good description to reproduce!
The regression came during SainSmart DDS120 support and adding AC/DC function.
