### ISSUE TITLE
Low image quality on exports

### ISSUE THREAD

**Issue by espindola** [OpenHantek/OpenHantek6022#353]
I am using f4d31c40aefa80c183cd9e3a2bb3e9a0e9240faf

The attached screenshots of demo mode illustrate the problems. The first one is that the resolution is low. It seems to have something to do with HiDPI displays. I was able to hack it locally by multiplying the width and heighth by 2, but I am not sure what the proper fix is.

The other problem is that some  lines are broken.

Everything looks good when running OpenHantek, it is only the exported pngs that are bad.

![20230225_214026](https://user-images.githubusercontent.com/42633/221382975-fa68e9bc-fb6c-4a78-be72-051409c2ac2f.png)
![20230225_211451](https://user-images.githubusercontent.com/42633/221382977-5e8ff4b9-c805-4b68-a784-7a6fcca2e3de.png)

**Computer environment (please complete the following information):**

I am running alpine linux 3.17, but I have been able to reproduce this with a debian stable chroot. Somehow the issue is not present on arch linux with version  3.3.2.1-1.

Given that it fails with a debian stable chroot, I suspect that somehow the sway or kernel version is relevant:

linux-lts-5.15.95-r0 
sway-1.7-r4

 - Video hardware: [e.g. *Intel Xeon ... Integrated Graphics*]

Intel Corporation HD Graphics 620 (rev 02)

 - OpenGL version: [e.g. *OpenGL 4.5, Mesa 19.0.3*]

Graphic: 4.6 (Compatibility Profile) Mesa 22.2.5 - GLSL version 1.20

 - Qt version: [e.g. *Qt 5.11.x*]

qt5-qtbase-5.15.6_git20221010-r0

 - C++ compiler version: [e.g. *gcc 8.3.x*]

gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924

**Scope device (please complete the following information):**

demo mode

**Comment by espindola** [comment]
I expanded the experiment by installing fedora 37 in a VM and producing screenshots from the vm  and then mounting the qcow2 image, chrooting into it and producing new screenshots. As far as I know, the only thing from alpine 3.17 being used in the chroot case is the wayland compositor (sway) and the kernel.

The 4 images are attached.
![fedora-in-vm-screenshot](https://user-images.githubusercontent.com/42633/221405373-68161ec4-626d-4253-9b58-995f96203c77.png)
![fedora-in-vm-hardcopy](https://user-images.githubusercontent.com/42633/221405375-45499dba-9de8-48e0-8744-31b7ea57906f.png)
![fedora-in-chroot-screen](https://user-images.githubusercontent.com/42633/221405376-2ab99cf1-7ad5-4be3-bcc8-ff27a24501a8.png)
![fedora-in-chroot-hardcopy](https://user-images.githubusercontent.com/42633/221405378-3948200d-a018-4f43-a1b0-90cf5d4ba515.png)

**Comment by iss000** [comment]
Just for reference - Fedora 36 (64 bit), KDE, Wayland. Attached are demo mode screenshot, hardcopy and the whole window captured with spectacle.
![20230226_140311](https://user-images.githubusercontent.com/1128663/221409610-e27bc0d0-cb1e-495d-91c2-47667e7aa873.png)
![20230226_140328](https://user-images.githubusercontent.com/1128663/221409612-993e22c4-85e6-4389-9a27-7d3f472b2230.png)
![Screenshot_20230226_140340](https://user-images.githubusercontent.com/1128663/221409613-fd915225-3b16-4a94-9b05-f282ad9bb79d.jpg)

**Comment by Ho-Ro** [comment]
> I was able to hack it locally by multiplying the width and heighth by 2, but I am not sure what the proper fix is.

@espindola 
Which screen resolution do you use?
Where did you multiply by 2?
Please give me a chance to understand the issue - I do not see this behaviour on my laptops (1280x800 and 1920x1080).

**Comment by Vascom** [comment]
I also have HiDPI monitor and the same problem.
I think we need option to set waveform line width.

**Comment by Ho-Ro** [comment]
> set waveform line width 

I already tried this long ago. Unfortunately this is not possible with the OpenGL graphics. The option for line width doesn't work - the width stays always "1".

**Comment by espindola** [comment]
> > I was able to hack it locally by multiplying the width and heighth by 2, but I am not sure what the proper fix is.
> 
> @espindola Which screen resolution do you use? Where did you multiply by 2? Please give me a chance to understand the issue - I do not see this behaviour on my laptops (1280x800 and 1920x1080).

My laptop resolution is 3200x1800, but sway is configured to scale it by 2 (" scale 2" in the config file).  I did the hack of multiplying by 2 by adding

```
     int sw = screenshot.width();
     int sh = screenshot.height();
+
+    screenshot = screenshot.scaled( sw *= 2, sh *= 2 );
+
```

I should probably try a KDE or Gnome session to compare. Will hopefully have that tonight.

**Comment by espindola** [comment]
Thinks look OK on my desktop, which has a 4K display (but is running arch, which has a newer version of sway).

**Comment by espindola** [comment]
> I also have HiDPI monitor 3840x2112 and the same problem. I think we need option to set waveform line width.

Are you using Wayland or X? Which compositor?

**Comment by Vascom** [comment]
> > I also have HiDPI monitor 3840x2112 and the same problem. I think we need option to set waveform line width.
> 
> Are you using Wayland or X? Which compositor?

Currently X11, Kwin.

**Comment by espindola** [comment]
I got the same issue with gnome instead of sway. Note that the take a regular screenshot (not via the OpenHantek menu) works just fine. One captured with grim is attached.

Looks like QT knows to do something different when outputting directly to the screen instead of to a QPixmap.

![20230227_17h41m03s_grim](https://user-images.githubusercontent.com/42633/221655961-9939c7ba-20b6-436e-a969-807f48b676c4.png)

**Comment by espindola** [comment]
One possible workaround is to disable the hdpi scaling just to produce the screenshot/hardcopy. This is what I got when I did that:

![20230227_175739](https://user-images.githubusercontent.com/42633/221658566-dd66f559-9ac5-4933-8e8c-5b9ce848854c.png)

**Comment by espindola** [comment]
> @espindola What are your values of sw and sh before you scale them? About 3200x1800 or 1600x900 (scale2)?
> 
> ```
>      int sw = screenshot.width();
>      int sh = screenshot.height();
> +    qDebug() << "screenshot size:" << sw << "x" << sh;
> 
>      screenshot = screenshot.scaled( sw *= 2, sh *= 2 );
> ```

I got: 

screenshot size: 1596 x 841

**Comment by Ho-Ro** [comment]
Ok, you get the downscaled size and upscale it to the correct 1:1 size.
Now the question, how to know if you're downscaling by 2 (or even by 4)?
A quick solution would be to make it a persistent config option that defaults to 1 and can be changed in the range of e.g. 1..8 - dunno if you have a better idea to detect it automatically.

**Comment by espindola** [comment]
> Ok, you get the downscaled size and upscale it to the correct 1:1 size. Now the question, how to know if you're downscaling by 2 (or even by 4)? A quick solution would be to make it a persistent config option that defaults to 1 and can be changed in the range of e.g. 1..8 - dunno if you have a better idea to detect it automatically.

Given that the image looks OK when drawing directly (not writing to the QPixmap), Qt must know this somehow (see https://github.com/OpenHantek/OpenHantek6022/issues/353#issuecomment-1446878548) , but I don't know where to look.

**Comment by Ho-Ro** [comment]
Please try the latest unstable - set scale factor in menu `Oscilloscope/Settings/Scope/Upscale exported images`

**Comment by espindola** [comment]
> Please try the latest unstable - set scale factor in menu `Oscilloscope/Settings/Scope/Upscale exported images`

The resolution is fixed, but some lines are still broken. Compare with https://github.com/OpenHantek/OpenHantek6022/issues/353#issuecomment-1446897149

![20230304_190321](https://user-images.githubusercontent.com/42633/222926458-6ad4f3dc-c5ff-40e1-9951-2535c2f95d29.png)

**Comment by Ho-Ro** [comment]
Which value did you set? 2?

**Comment by espindola** [comment]
> Which value did you set? 2?

Yes, 2.

**Comment by Ho-Ro** [comment]
strange, then it should give the same result as your
```
+
+    screenshot = screenshot.scaled( sw *= 2, sh *= 2 );
+
```

But now another *shot in the dark* -> new unstable

**Comment by espindola** [comment]
> But now another _shot in the dark_ -> new unstable

Fixed!
![20230305_144845](https://user-images.githubusercontent.com/42633/222971215-b3092f1c-7304-425d-8205-08c1ed352a53.png)
