### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by thalst** [OpenHantek/OpenHantek6022#36]
When using single trigger, the spike may not be exactly centered. Consequently, if the time/div is expanded, the signal goes out of screen. 

A good solution would be a horizontal scroll, option added. Zoom function could tackle the problem, but in  this process, another useful feature that could be implemented is a kind of data acquisition menu that allows to specify how much data a user wants to be saved.

.

**Comment by Ho-Ro** [comment]
@thalst Please check, no scroll, but trace is always aligned with trigger mark on screen.

**Comment by Ho-Ro** [comment]
The pdf/png export doesn't support this behaviour currently, don't use it now!

**Comment by Ho-Ro** [comment]
The pdf/png export fixed since version 3.0.1
