### ISSUE TITLE
No graphics output - windows 10 3.3.2.2

### ISSUE THREAD

**Issue by squelch41** [OpenHantek/OpenHantek6022#360]
Openhantek loads but, with the 'scope and in demo mode, I just get a black window.
Console output as screenshot here:
![image](https://user-images.githubusercontent.com/10134966/226963760-0124f9c4-5785-4c76-9270-8f7e9d834c6d.png)

Openhantek window screenshot:
![image](https://user-images.githubusercontent.com/10134966/226964249-4b58c1d2-c530-45ee-b7cb-0cfad56c8fae.png)

Using Windows 10, core i5-4300U laptop 8gb ram and integrated gfx

**Comment by squelch41** [comment]
Oh yes, forgot to say, I tried that (and -e which I think is equivalent?)
get the following error:
![image](https://user-images.githubusercontent.com/10134966/226974091-54d910da-bc52-4a51-9688-4e29b3aa392d.png)


and a white window:
![image](https://user-images.githubusercontent.com/10134966/226974200-5b0457ab-85de-49fa-90d6-5a7bc215a8a2.png)

**Comment by DaPa** [comment]
Both openhantek_3.3.2.2-1_win_x64 and latest openhantek_3.3.2.2-9-g383ecd0-1_win_x64 work fine here (on Windows 10 Pro, 21H2, x64):
![image](https://user-images.githubusercontent.com/4947697/229496452-261a4b17-bafb-49b0-948e-c63ef2d11b7d.png)
![image](https://user-images.githubusercontent.com/4947697/229496561-d4cb3c87-3c83-4eb6-b089-dad867deeb6c.png)

**Comment by sqliuchang** [comment]
I have the same issue. And my PC is surface pro 3 which is also i5-4300u with 8G ram.

**Comment by Ho-Ro** [comment]
> Version 3.3.2 is fine.

@gitguest0 3.3.2 used MSVC. Could this issue be a regression from the switch to mingw64?

**Comment by gitguest0** [comment]
Probably, seems like a problem with very old Intel graphics drivers.
I just tested it on a Intel 7th gen Windows Tablet with no issues.

**Comment by fabi9163** [comment]
I've the same bug, also Surface pro 3...is there now the required versio 5.15.11 available to build a new release which maybe would fix this?
