### ISSUE TITLE
Changing timebase crashes

### ISSUE THREAD

**Issue by dzid26** [OpenHantek/OpenHantek6022#373]
**Describe the bug**
Changing timebase to anything other than initial 1ms causes program to close and settings to reset (dark theme goes light).

1. Open demo or real scope - plot is displayed correctly, everything else seems to work
2. Change timebase - Program closes!
3. Open the program again - settings are lost!

**Expected behavior**
To be able to change the timebase.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Computer environment (please complete the following information):**
 - OpenHantek version: `openhantek_3.3.2.2-1_win_x64`
 - OS: Win11 x64

Note:
It works ok in previous `openhantek_3.3.2.1-1_win_x64` and latest _unstable_ `openhantek_3.3.2.2-23-g9a3d953-1_win_x64`

<img width="810" alt="image" src="https://github.com/OpenHantek/OpenHantek6022/assets/841061/46c591e1-6f11-461a-b076-88418013bb07">

**Comment by Ho-Ro** [comment]
You mentioned above that openhantek_3.3.2.2-23-g9a3d953-1_win_x64 is buggy as well as being ok.
Please confirm that latest unstable is OK, while latest release 3.3.2.2 crashes.
If this is the case then the bugs #363 and #365 were fixed today with #372 - now in unstable.

**Comment by dzid26** [comment]
Sorry, openhantek_3.3.2.2-1_win_x64  is not working.  I corrected the issue.

**Comment by Ho-Ro** [comment]
Thx for clarification, this long lasting issue blocked my freeze for the next release (coming soon).
