### ISSUE TITLE
Add a new device: Hantek 1070

### ISSUE THREAD

**Issue by ccorrea97** [OpenHantek/OpenHantek6022#387]
Hello, how are you?

I'm currently working with a Hantek IDSO1070A. What I aim to do is to build a simple custom software which retrieves data from the oscilloscope and, with a specific setting, plot the curves for each channel. I'm struggling with the very beginning of it: communicate the Hantek with my code. This seems to be not an easy task (tried with PyVISA but not working). I was wondering if some of you worked on it or see it viable to do. 

The solution I would like, taking in consideration the 'add a new device' section in the readme file, is to have the option to add the Hantek IDSO1070A.

Thank you very much in advance, hopefully you can help me.

**Comment by Ho-Ro** [comment]
Sorry, but the communication structure of this 1070 scope is so different from the scopes supported by OH6022 - they all are based on the Cypress EzUSB chip that streams the data from the ADCs directly w/o buffering. OH6022 has been optimised to get the max out of these cheap HW.
But there exist other projects for the 1070, e.g. this one https://github.com/hhornbacher/idso1070-protocol
