### ISSUE TITLE
No traces seen under v3.3.3

### ISSUE THREAD

**Issue by softfoot** [OpenHantek/OpenHantek6022#388]
In demo mode (and normal running) of v3.3.3 I see no traces - all the text messages (measurements etc) are present - just NO traces:
v3.3.2.1 works correctly.
Altering trigger points and other settings doesnt help.
Running under Win7 PRO 64bit
Single monitor 1920/1080
Built in display on Laptop ThinkPad T410 (I think)
Reproduceable in DEMO mode

**Comment by Ho-Ro** [comment]
@gitguest0 could you please check if your build system change can cause this issue.

**Comment by Ho-Ro** [comment]
@softfoot you could check the msvc build from latest unstable release

**Comment by Ho-Ro** [comment]
As @softfoot did not provide the requested info I suppose he's happy with the MSVC build. I will close now.
