### ISSUE TITLE
Need to correct Timebase and Samplerate setting

### ISSUE THREAD

**Issue by Vascom** [OpenHantek/OpenHantek6022#4]
It is impossible to set desired Timebase and Samplerate simultaneously.

For example I want 100 ns and 12 Msps but it is always switched to maximum samplerate on lower timebases.

This is a very annoying bug and very bad for user experience.

**Comment by Ho-Ro** [comment]
Honestly speaking I do not like the idea that the user selects the sample rate - but OpenHantek is the legacy of a handful of developers over the last nine years and therefore some behaviour is difficult to change. 
My use case of a scope is setting voltage/div and time/div to get the interesting view on screen. 
The scope should set sampling rate accordingly (same as for voltage/div set by user -> scope selects appropriate input gain step).
With the limitation that we have a fixed recording length of 20480 bytes, we have to meet the diverging requirements:
* Good detail resolution (that requires the **highest** possible sampling rate).
* Reliable software trigger (we need a long recording time to catch an edge -> that requires the **lowest** possible sampling rate).
* A stable display (that requires as many points on the screen as possible -> high sampling rate but at least you need a recording time of about double length of the screen size -> lower sampling rate).

**Comment by Vascom** [comment]
I would not like to rely entirely on automatic settings.
Especially if I can set manually, as on hardware oscilloscopes.

**Comment by Vascom** [comment]
Or just remove the Samplerate setting. Or hide it. But leave the opportunity to set the maximum value so that the data does not fail when transferring via USB.

**Comment by Vascom** [comment]
Because on 30Msps I still see artifacts like this:
![oh_2](https://user-images.githubusercontent.com/550017/56959787-59892e00-6b57-11e9-9fc9-cd57b905262b.png)
16Msps has more clear image.

**Comment by Ho-Ro** [comment]
02b6bd4e Now only the second highest rate is selected as maximum default (24 MS/s for CH1 only, 12 MS/s for CH1&CH2) but 30 or 16 can be chosen manually at the cost of reduced stability.
