### ISSUE TITLE
Support for Hantek 1008c

### ISSUE THREAD

**Issue by sebastianfelipe** [OpenHantek/OpenHantek6022#40]
Hi, I wanna know if there is some kind of support for Hantek 1008c. Tried to find it but I haven't got any information about it.

I'd like to use the device natively on OSX but right now I can't :/

Thanks,
Sebastián.

**Comment by Ho-Ro** [comment]
Hi Sebastián, support for 1008 is neither available nor planned. Implementing this 8 channel scope into OpenHantek6022 without access to the HW of this device is impossible for me. If someone provides a working solution without degradation of the main target of this program (Hantek 2 channel devices and compatibles) I'll happily accept a pull request.
