### ISSUE TITLE
Noob question: DSO-5200A support?

### ISSUE THREAD

**Issue by LuchkaOnTheMoon** [OpenHantek/OpenHantek6022#412]
Good morning people,

as per title, a very noob question: as OpenHantek6022 is a fork of OpenHantek project (which build is unfortunately failing now, sigh), should I expect that this fork is still supporting DSO-5200A (and maybe other DSO-2xxx scopes) or not?

Asking this since I'm looking for an entry level USB scope, and Hantek DSO-2150/2250/etc. have a better analog BW than 6022BE.

A side question: does OpenHantek6022 support acquiring both analog and logic signals of 6022BL at the same time?

Thank you very much in advance for your patience.

**Comment by LuchkaOnTheMoon** [comment]
A DSO-5200A is on the road to my lab, I'll test by myself then I'll leave a comment to support others.

**Comment by Ho-Ro** [comment]
> should I expect that this fork is still supporting DSO-5200A (and maybe other DSO-2xxx scopes) or not?

Nope, OH6022 supports only the 6022 and compatible scopes (based on Cypress EzUSB chip) advertised as 2 channel 48 Megasamples/second, even if it is useful only up to 24 MS/s.

You could check my branch [last_legacy_support](https://github.com/OpenHantek/OpenHantek6022/tree/last_legacy_support).
The README says:
>DSO2xxx Series and DSO52xx Series support is still in but untested due to missing devices.
