### ISSUE TITLE
Only DC input mode available ..

### ISSUE THREAD

**Issue by bmentink** [OpenHantek/OpenHantek6022#43]
I don't know if this is a bug or a work-in-progress ... but there in only a pull-down for DC input, no AC input is shown ..

Please move this into "Enhancements" if this is still to do ..

Cheers for the great work .. :)

**Comment by Vascom** [comment]
Do you have an AC input device?

**Comment by bmentink** [comment]
I have a 6022/BE, is this DC only maybe?

**Comment by Vascom** [comment]
Yes. 6022BE only DC coupled.

**Comment by bmentink** [comment]
Many thanks, will close this issue .. cheers

**Comment by Ho-Ro** [comment]
I wrote a small [AC HW modification HowTo](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/HANTEK6022_AC_Modification.pdf) for 6022 devices, that gives you programmable AC/DC coupling.
