### ISSUE TITLE
no 100x probe option?

### ISSUE THREAD

**Issue by sceptre357** [OpenHantek/OpenHantek6022#53]
I see in the OpenHantek6022 example screenshot a drop-down box with x100 selected. Also cannot select AC option.

![image](https://user-images.githubusercontent.com/60056540/73334927-f4f72d00-42a8-11ea-83d9-e4f8351c9c6a.png)

 I've downloaded v3.0.1 for Debian but i see only a check box for a x10 probe.  
![image](https://user-images.githubusercontent.com/60056540/73335011-2b34ac80-42a9-11ea-9dae-cc016f1bf2e6.png)

how can I use my 100x probe? Years ago I always use my 100x probe for troubleshooting inverters AC 220v output. it works fine with 6022 Original software.  please help, thank you.

**Comment by Ho-Ro** [comment]
You're using the last stable (debian-like speaking) release:
![image](https://user-images.githubusercontent.com/12542359/73339484-34a62080-4279-11ea-9a0a-2cfeaf19b7df.png)
while the screen shot shows the (unstable) build 593 from 2020-01-21: 
![image](https://user-images.githubusercontent.com/12542359/73339571-530c1c00-4279-11ea-9dab-4570f6471915.png)

Three possibilities:
- If you want to be always up to date (and are familiar with git), get a local clone of the the repo and [create your own version](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/build.md#linux). 
- Get the zipped source code and build your snapshot.
- Wait for the next release.

![image](https://user-images.githubusercontent.com/12542359/73342343-a6349d80-427e-11ea-84a4-7b81ce3a08e9.png)
