### ISSUE TITLE
USBee-DX Support

### ISSUE THREAD

**Issue by Deusex25** [OpenHantek/OpenHantek6022#57]
Hi guys.

Recently I got my hands on a clone of USBee-DX device. This is combined logic analyzer and oscilloscope.
I was hoping to make it working under Linux with Sigrok PulseView software, but unfortunately it supports only analyzer side.
Googling this issue brought me to few articles, with information, that this devices are hardware compatible to Saleae logic analysers and stating that Handek 6022 is basically improved clone of the same USBee-DX...
Indeed, checking the drawings I've found, led me to conclusion that at least general configuration is very similar: both devices are using Cypress FX2 chip (100-pin CY7C68013A-100 in case of Hantek and  56-pin Cypress CY7C68013A-56 in case of USBee-DX clone), which is getting information from ADCs (one dual ADC AD9288 and two single TLC5510 respectively) over B and D ports, and both devices are getting the firmware from PC software.

Winged by this information I started experimenting with different VID/PID values, trying to get USBee-DX clone represent itself as 6022, and even got it detected as Hantek and driver loaded. Unfortunately OpenHantek software shows an error, stating that it cannot load the firmware.

My question is: will it be possible to get a support for USBee-DX compatible oscilloscopes? What can I do from my side? I'm programming a bit (C & C++), but I'm not professional. I do not know, from which side to approach to this issue.

**Comment by Ho-Ro** [comment]
This is mainly a question of the firmware. It makes no sense to discuss it here unless Ho-Ro/Hantek6022API#6 isn't solved.
