### ISSUE TITLE
Hantek 6004BD support

### ISSUE THREAD

**Issue by dickshaydle** [OpenHantek/OpenHantek6022#6]
Hi there,

are there any approaches in supporting the 6004BD series, especially the Hantek 6204BD in linux?

I just found that the serial communication chip is a CY7C68013A (FX2LP) and that it can be reverse engineered with the Hantek SDK and a Windows in a virtual machine for the 6022BE. rpcope1 has made some progress (https://github.com/rpcope1/Hantek6022API/blob/master/REVERSE_ENGINEERING.md). 
Any more tips if i would try to implement it?

**Comment by Ho-Ro** [comment]
Hi dickshaydle, did you read [how to add a new device](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/adddevice.md)?
Unfortunately I'm not able to implement a new device that I do not own. I cloned this repo to improve my own 6022 device according to my needs. Also I see that the 6004 has a complete different HW setup than 6022. FXLP2 is able to stream directly (theoretically) with max 48 MB/s, practically it works well with 24 MB/s. 6004 datasheet talks about 1GS/s, this is only possible if the scope samples high-speed into an on-board RAM and transfers later with lower speed. 6022 on the other hand has no local frame and streams directly to USB.
But if you make it, I will gladly add your pull-request, provided that the 6022 functionality doesn't suffer.
Martin
