### ISSUE TITLE
Saving or Streaming Data

### ISSUE THREAD

**Issue by 2014siavash** [OpenHantek/OpenHantek6022#64]
Hi,

I need to record 1 min (60 secs) data with an arbitrary chosen sample rate. But I couldn't find a way for doing this. Could you guide me what can I do for this?

I am using Hantek 6022bl.

Thanks

**Comment by vizkoze** [comment]
Use sigrok to do that.
________________________________

**Comment by Ho-Ro** [comment]
> I need to record 1 min (60 secs) data

I assume you want to record analog data (CH1 & CH2), as vizkoze I would also propose the cli tools of *sigrok*. Another option is to use the [python bindings](https://github.com/Ho-Ro/Hantek6022API) and write an own script.
