### ISSUE TITLE
Openhantek rollback

### ISSUE THREAD

**Issue by JuttDB** [OpenHantek/OpenHantek6022#65]
hello.
          I am using windows 10 with hantek6022BE. I was able to test the openhantek. now I like to go back to original firmware. can you please guide me to revert the openhantek firmware to original hantek6022BE.

**Comment by vizkoze** [comment]
Just unplug the device, stop openhantek and start hantek software. It should load the firmware stored in the official hantek software
________________________________

**Comment by JuttDB** [comment]
i did the same thing but original hantek software searching for the device. it's detecting device any more

**Comment by vizkoze** [comment]
Have you tried turning it off and on again? 😉
________________________________

**Comment by JuttDB** [comment]
yes, I removed the USB and connect again. even on the pc side I also did reset.

**Comment by JuttDB** [comment]
is there anything that I need to do with Zadig software again.

**Comment by Ho-Ro** [comment]
Did you read the Zadig [FAQ](https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it)?

**Comment by JuttDB** [comment]
after uninstalling from Universal Serial Bus devices everything is working again.

**Comment by fire1** [comment]
Change USB port! I notice this but after changing USB port (to use original, saleae logic analyzer and OpenHantek) I use all without any software issues
