### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by alimoche** [OpenHantek/OpenHantek6022#71]
Spanish translation is missing, please consider this initial translation (attached file), many words are not translated becasue they are the same and/or do not have a clear translation, e.g. CH1, AC, DC, ...

[openhantek_es.zip](https://github.com/OpenHantek/OpenHantek6022/files/4433512/openhantek_es.zip)

**Comment by Ho-Ro** [comment]
Thx, merged with f51cd22.
