### ISSUE TITLE
Recording a waveform over several seconds

### ISSUE THREAD

**Issue by flagoworld** [OpenHantek/OpenHantek6022#72]
Is it possible to record several seconds of a waveform and then go back and look at the waveform in fine detail? I need to watch for certain noise/interruptions that seems to be happening intermittently in my signal.

**Comment by Ho-Ro** [comment]
You should use [capture_6022.py](https://github.com/OpenHantek/OpenHantek6022/issues/56#issuecomment-604696198) for long time recording. It saves CSV data that can be analysed with e.g. matplotlib, have a look at [fft_from_capture.py](https://github.com/Ho-Ro/Hantek6022API/blob/master/examples/fft_from_capture.py) as an example how to handle the captured data.
