### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by LubuntuSharp** [OpenHantek/OpenHantek6022#75]
**Describe the bug**
A division by zero comes out

**To Reproduce**
GDB SHOWS OpenHantek6022-3.0.3/openhantek/src/hantekdso/hantekdsocontrol.cpp
LINE 549 result.data[channel].resize( sampleCount / rawDownsampling );
rawDownsampling can happen to be equal to zero at run-time (I solved by defaulting resize argument to 1 instead of getting division by zero)

System info:
 - OpenHantek version: OpenHantek6022-303
 - OS: Lubuntu 16.04
 - Distribution, version: x86 32 bit
 - Video hardware: [*Intel Integrated Graphics*]
 - C++ compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Scope device (please complete the following information):**
 - Device  *Hantek 6022BE, ...*]
 - Program top line [e.g. *OpenHantek6022 (Build ...) - Device ... (FW 0205)*]

**Additional context**
I run with --useGLES option

**Comment by Ho-Ro** [comment]
ok, from data flow it shouldn't happen:

    unsigned HantekDsoControl::getRecordLength() const {
        unsigned rawsize = SAMPLESIZE_USED; // = 20000
        rawsize *= this->downsamplingNumber; // take more samples
        rawsize = ( (rawsize + 1024) / 1024 + 2 ) * 1024; // adjust for skipping of minimal 2018 leading samples
        //printf( "getRecordLength: %d\n", rawsize );
        return rawsize;
    }

    ...

    const unsigned rawSampleCount = unsigned( isFastRate() ? rawData.size() : (rawData.size() / 2) );
    //printf("cRDTS, rawSampleCount %lu\n", rawSampleCount);
    if ( 0 == rawSampleCount) // nothing to convert
        return;
    ...
    unsigned sampleCount = (rawSampleCount > 1024) ? ((rawSampleCount - 1024)/1000 - 1)*1000 : rawSampleCount;
    ...
    unsigned rawDownsampling = sampleCount / SAMPLESIZE_USED;
    ....
    result.data[channel].resize( sampleCount / rawDownsampling );

but I've included more safeguarding with   a933b52
