### ISSUE TITLE
Requirement for Signed-off-by trailer missing from readme

### ISSUE THREAD

**Issue by DavidRisch** [OpenHantek/OpenHantek6022#79]
The is no mention of the `Signed-off-by:` requirement in README.md but it is enforced by the DCO bot. This should be mentioned somewhere, maybe with a link to https://github.com/probot/dco/blob/master/README.md. Maybe a CONTRIBUTING.md?

**Comment by Ho-Ro** [comment]
Done with f1b0ab8
