### ISSUE TITLE
Add an OpenHantek Icon in Windows Version.

### ISSUE THREAD

**Issue by AndreasDerFuchs** [OpenHantek/OpenHantek6022#86]
This is just a proposal:
Based on the openhantek.png an an input image to 'Greenfish Icon Editor Pro' I created the an icon. Maybe you want to add it to the Window-Version of OpenHantek.exe (or next to it), see the icon file in the attached Zip-File.
[openhantek_icon.zip](https://github.com/OpenHantek/OpenHantek6022/files/4571443/openhantek_icon.zip)

**Comment by Ho-Ro** [comment]
0ebab7c added [this icon file](https://github.com/OpenHantek/OpenHantek6022/blob/master/cmake/OpenHantek.ico) based on the [official OpenHantek6022 icon](https://github.com/OpenHantek/OpenHantek6022/blob/master/openhantek/res/images/OpenHantek.png) into the Openhantek*.zip files.
Thx for the proposal.

![image](https://user-images.githubusercontent.com/12542359/80954094-03e80100-8dfd-11ea-86c8-dbab322a90c8.png)
