### ISSUE TITLE
Add option to save more data to file

### ISSUE THREAD

**Issue by Vascom** [OpenHantek/OpenHantek6022#9]
Can you please add option to save more data to file. Not only 20000 samples.
If it can not be save continuously than at least incontinuously.

So user can set multiplier for example 2x20k, 3x20k, etc.

It will be good for postprocessing in other apps like octave.

**Comment by Ho-Ro** [comment]
Maybe not exactly what you proposed - but...
Please test the release v2.09 (08d1aa2), I've added timebase 20, 50 and 100 ms/div, the slowest setting collects 200000 samples (2s record length). If you want longer traces you have also the chance to use sigrok that allows almost unlimited sample size.
